create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  target_type text not null check (target_type in ('program', 'announcer')),
  target_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);

create index if not exists idx_user_favorites_user on user_favorites(user_id);
create index if not exists idx_user_favorites_target on user_favorites(target_type, target_id);

alter table user_favorites enable row level security;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_favorites' AND policyname = 'Users manage own favorites') THEN
    CREATE POLICY "Users manage own favorites"
      ON user_favorites
      FOR ALL
      TO authenticated
      USING (user_id = auth.uid())
      WITH CHECK (user_id = auth.uid());
  END IF;
END;
$$;
