create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null on delete cascade,
  target_type text not null check (target_type in ('program', 'announcer')),
  target_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);

create index if not exists idx_user_favorites_user on user_favorites(user_id);
create index if not exists idx_user_favorites_target on user_favorites(target_type, target_id);

alter table user_favorites enable row level security;

create policy "Users manage own favorites"
  on user_favorites
  for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
